phrase:
  access_token: ${{ secrets.PHRASE_ACCESS_TOKEN }}
  project_id: "df9014814bc8b52293c8baab4e05defa"
  git:
    repository_url: "git@github.com:BrendowLincoln/phrase-poc.git"
    branch: "main"
    file_format: yaml
    push:
      sources:
        - file: ./locales/pt.yml
          params:
            locale_id: "pt"
    pull:
      targets:
        - file: ./locales/pt.yml
          params:
            locale_id: "pt"
  default_locale: "pt"
